# Generated by Django 4.0.7 on 2023-07-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRitual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horaEvento',
            field=models.TimeField(null=True, verbose_name='Hora Evento'),
        ),
    ]
