# Generated by Django 4.0 on 2023-06-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRitual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadore',
            name='foto_id',
            field=models.ImageField(blank=True, upload_to='fotos_id'),
        ),
    ]
