# Generated by Django 4.0 on 2023-07-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRitual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='anotaciones',
            field=models.TextField(blank=True, verbose_name='Anotaciones (opcional)'),
        ),
        migrations.AlterField(
            model_name='reservasmesa',
            name='anotaciones',
            field=models.TextField(blank=True, verbose_name='Anotaciones (Opcional)'),
        ),
        migrations.AlterField(
            model_name='trabajadore',
            name='anotaciones',
            field=models.TextField(blank=True, verbose_name='Anotaciones (opcionales)'),
        ),
    ]
