# Generated by Django 4.0 on 2023-07-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRitual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasmesa',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
